
image: node:8

stages:
  - build
  - test
  - deploy

before_script:
  - npm install 

cache:
    paths:
    - ./node_modules

build:
  script:
    - npm run build:gitlab
  artifacts:
    paths:
      - dist/

pages:
  stage: deploy
  script:
  - mv dist public
  artifacts:
    paths:
    - public
  only:
  - master
