name: Build Angular on Pull Request Created

on:
  pull_request:
    types: [opened]   # dispara somente quando o PR é aberto
    branches:
      - development   # apenas PRs com destino para a branch "development"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        working-directory: ./FrontEnd

      - name: Build Angular app
        run: npm run build
        working-directory: ./FrontEnd

